version: "3.9"
services:
  web:
    container_name: my-hello-world
    build: .
    image: jimeoler/hello-world:latest
    ports:
      - "4433:80"
    restart: unless-stopped
    labels:
      - "support_url=https://yourwebsite.com"
      - "project_url=https://github.com/JimEOler/hello-world"
